/**
 * TD(λ) self-play training orchestrator.
 *
 *   node scripts/train.js --games 120000 --hidden 80
 *   node scripts/train.js --resume ckpt.json --games 200000
 *
 * Workers each play batches from the latest master weights and post back
 * deltas, which are merged asynchronously (parameter-server style). Every
 * checkpoint the master is benchmarked against pubeval and saved.
 */

import { Worker } from 'node:worker_threads';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { availableParallelism } from 'node:os';

import { createNet, loadNet, exportNet } from '../src/engine/net.js';
import { netVsPubeval, xorshift } from './td.js';

const args = {};
for (let i = 2; i < process.argv.length; i += 1) {
  const a = process.argv[i];
  if (a.startsWith('--')) args[a.slice(2)] = process.argv[i + 1];
}

const TARGET = Number(args.games || 120000);
const HIDDEN = Number(args.hidden || 80);
const BATCH = Number(args.batch || 32);
const WORKERS = Number(args.workers || Math.max(1, Math.min(8, availableParallelism() - 2)));
const CHECK_EVERY = Number(args['checkpoint-every'] || 5000);
const BENCH_GAMES = Number(args['bench-games'] || 400);
const LAMBDA = Number(args.lambda || 0.7);
const OUT = args.out || 'src/engine/weights.js';
const CKPT_DIR = args['ckpt-dir'] || 'checkpoints';
const SEED = Number(args.seed || 20260802);

const alphaAt = (games) => (games < 30000 ? 0.1 : games < 70000 ? 0.05 : 0.02);

const master = args.resume
  ? loadNet(JSON.parse(readFileSync(args.resume, 'utf8')))
  : createNet(HIDDEN, xorshift(SEED));
let games = Number(args['resume-games'] || 0);
let plies = 0;
let abandoned = 0;
let lastCheck = games;
const benchRng = xorshift(SEED ^ 0x9e3779b9);
const t0 = Date.now();

mkdirSync(CKPT_DIR, { recursive: true });

function snapshotWeights() {
  return {
    w1: Float64Array.from(master.w1),
    b1: Float64Array.from(master.b1),
    w2: Float64Array.from(master.w2),
    b2: Float64Array.from(master.b2),
  };
}

function checkpoint(final = false) {
  const stamp = `${games}`;
  const file = `${CKPT_DIR}/ckpt-${stamp}.json`;
  writeFileSync(file, JSON.stringify(exportNet(master, 6)));
  const bench = netVsPubeval(master, final ? 2000 : BENCH_GAMES, benchRng);
  const mins = ((Date.now() - t0) / 60000).toFixed(1);
  console.log(
    `[${mins}m] games=${games} avgPlies=${(plies / Math.max(1, games)).toFixed(1)} ` +
      `abandoned=${abandoned} alpha=${alphaAt(games)} | vs pubeval (${bench.games}): ` +
      `win ${(bench.winRate * 100).toFixed(1)}% ppg ${bench.ppg.toFixed(3)}`,
  );
  return bench;
}

console.log(
  `training: target=${TARGET} hidden=${HIDDEN} workers=${WORKERS} batch=${BATCH} lambda=${LAMBDA}`,
);

const workers = [];
let done = 0;

function dispatch(worker) {
  worker.postMessage({
    type: 'run',
    games: BATCH,
    alpha: alphaAt(games),
    lambda: LAMBDA,
    weights: snapshotWeights(),
  });
}

function finish() {
  console.log('--- final benchmark ---');
  checkpoint(true);
  const data = exportNet(master, 5);
  const body =
    `/**\n` +
    ` * Trained evaluation-network weights. Generated by scripts/train.js\n` +
    ` * (TD-lambda self-play, ${games} games, ${HIDDEN} hidden units).\n` +
    ` * Regenerate with: node scripts/train.js\n` +
    ` */\n` +
    `export default ${JSON.stringify(data)};\n`;
  writeFileSync(OUT, body);
  console.log(`wrote ${OUT} (${(body.length / 1024).toFixed(0)} KB)`);
  for (const w of workers) w.terminate();
}

for (let i = 0; i < WORKERS; i += 1) {
  const worker = new Worker(new URL('./train-worker.js', import.meta.url), {
    workerData: { seed: SEED + 1000 * (i + 1), hidden: HIDDEN },
  });
  worker.on('message', (msg) => {
    if (msg.type !== 'done') return;
    for (const key of ['w1', 'b1', 'w2', 'b2']) {
      const m = master[key];
      const d = msg.delta[key];
      for (let j = 0; j < m.length; j += 1) m[j] += d[j];
    }
    games += msg.games;
    plies += msg.plies;
    abandoned += msg.abandoned;

    if (games - lastCheck >= CHECK_EVERY) {
      lastCheck = games;
      checkpoint();
    }
    if (games >= TARGET) {
      done += 1;
      worker.unref();
      if (done === 1) finish();
      return;
    }
    dispatch(worker);
  });
  worker.on('error', (err) => {
    console.error('worker error', err);
    process.exit(1);
  });
  workers.push(worker);
  dispatch(worker);
}
